export const SET_USER = 'SET_USER';
export const SET_WALLET = 'SET_WALLET';
export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const SET_EXCHANGE_RATE = 'SET_EXCHANGE_RATE';
export const SET_DELETE_EXPENSE = 'SET_DELETE_EXPENSE';
